# Alacritty configuration file using TOML format
# Documentation can be found at https://alacritty.org/config-alacritty.html

# Import additional configuration files (e.g., color themes)
# import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

#[shell]
# The program to execute when the terminal starts (e.g., zsh, bash, wsl)
#program = "/bin/zsh"
# Arguments passed to the shell program
# args = ["--login"]

[general]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]


[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"


[cursor]
# The cursor style
style = { shape = "Block" } # Options: "Block", "Underline", "Beam"
# If true, the cursor is temporarily hidden when typing
unfocused_hollow = false

[window]
# Window opacity (0.0 to 1.0)
opacity = 0.9

[scrolling]
# The number of lines in the scrollback buffer
history = 10000

